#! /usr/bin/env python
# encoding: utf-8


def configure(cnf):
    cnf.define('LIBDIR', cnf.env['LIBDIR'])
    cnf.define('DATADIR', cnf.env['INSTALL_DATA_DIR'])
    cnf.write_config_header('config.h')

    if cnf.options.debug:
        cnf.env.CFLAGS += ['-g3', '-O0', '-Wall']

def build(bld):
    bld(
        features='c cstlib',
        vala_target_glib = '2.44',
        packages         = 'json-glib-1.0 gtk+-3.0 posix cajami',
        target           = 'ajamiobjects',
        uselib           = 'JSON GTK JACK LIBXML FFTW OSC M DL GMODULE',
        vala_resources   = '../data/ajami.gresource.xml',
        use              = 'hvmeter',
        vapi_dirs        = '.',
        includes         = '.',
        source           = 'Ajami.vala AjamiApp.vala AjamiWindow.vala AjamiState.vala AjamiScenes.vala AjamiCompressor.vala Stereo.vala InTrim.vala'
                           ' AjamiSpectrum.vala AjamiHelp.vala AjamiLimiter.vala LimiterBackend.vala AjamiArgs.vala AjamiGEQ.vala AjamiPreferences.vala'
    )
    ajami = bld(
        features         = 'c cprogram glib2',
        vala_target_glib = '2.44',
        packages         = 'json-glib-1.0 gtk+-3.0 posix cajami',
        target           = 'ajami',
        uselib           = 'JSON GTK JACK LIBXML FFTW OSC M DL GMODULE',
        use              = 'hvmeter ajamiobjects',
        vala_resources   = '../data/ajami.gresource.xml',
        vapi_dirs        = '.',
        includes         = '.',
        source           = '../data/ajami.gresource.xml io.c rms.c process.c'
                           ' hdeq.c plugin.c compressor-ui.c preferences.c spline.c geq.c'
    )
