#! /usr/bin/env python
# encoding: utf-8


def configure(cnf):
    cnf.define('LIBDIR', cnf.env['LIBDIR'])
    cnf.define('DATADIR', cnf.env['INSTALL_DATA_DIR'])
    cnf.write_config_header('config.h')

    if cnf.options.debug:
        cnf.env.CFLAGS += ['-g3', '-O0', '-Wall']

def build(bld):
    valaobjs = bld(
        features         = 'c cstlib',
        target           = 'ajamiobjects',
        vala_target_glib = '2.38',
        install_binding  = False,
        packages         = 'gtk+-3.0 posix cajami',
        uselib           = 'GTK',
        use              = 'hvmeter',
        vala_resources   = '../data/ajami.gresource.xml',
        vapi_dirs        = '.',
        includes         = '.',
    )
    valaobjs.source = 'Ajami.vala AjamiApp.vala AjamiWindow.vala AjamiScenes.vala AjamiCompressor.vala'
    valaobjs.source += ' AjamiHelp.vala AjamiLimiter.vala AjamiArgs.vala AjamiGEQ.vala'
    valaobjs.source += ' AjamiSpectrum.vala AjamiPreferences.vala'

    ajami = bld(
        features       = 'c cprogram glib2',
        target         = 'ajami',
        uselib         = 'GTK JACK LIBXML FFTW OSC M DL GMODULE',
        use            = 'ajamiobjects hvmeter',
        includes       = '.',
        source         = '../data/ajami.gresource.xml'
    )
    ajami.source += ' io.c limiter-ui.c rms.c scenes.c process.c state.c'
    ajami.source += ' hdeq.c plugin.c compressor-ui.c intrim.c preferences.c'
    ajami.source += ' spline.c geq.c stereo.c'
